### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by array42-zz** [oranav/i9300_emmc_toolbox#3]
Had to modify the Makefile slightly, to allow asm and C11 specific syntax:
CFLAGS += -fno-stack-protector -fno-common -fomit-frame-pointer -fPIE -static -O0 -std=gnu11

Just in case someone needs it also.

**Comment by oranav** [comment]
Fixed in b276f4959927de3d74bd07ad0a40e50098851c75. Thanks!
